apiVersion: v1
kind: Pod
metadata:
  name: pod-volume
spec:
  containers: 
  - name: nginx-container
    image: nginx:stable
    volumeMounts:
    - name: primeiro-volume
      mountPath: /volume-dentro-do-container
  - name: jenkins-container
    image: jenkins/jenkins:latest
    volumeMounts:
    - name: primeiro-volume
      mountPath: /volume-dentro-do-container
  volumes:
  - name: primeiro-volume
    hostPath:
      path: /volume-do-host
      type: DirectoryOrCreate